// Gyakori magyar es nemzetkozi keresztnevek (a vendeg "Név" mezojebol a megszolitashoz).
// Tartalom: magyar noi es ferfi utonevek (gyakorisagi lista + ritkabbak), becezett alakok (Zsófi, Kati, Tomi...),
// a hazankban gyakori kulfoldi nevek (angol, nemet, szlovak, roman, szerb, olasz, spanyol, arab, azsiai...).
// NEM kerulhet bele olyan szo, ami elsosorban vezeteknev (Kovács, Nagy, Szabó, Simon, Fekete, Illés...): a nevek.js a lista
// alapjan dont a "vezeteknev utonev" / "utonev vezeteknev" sorrendrol, ezert a vezeteknevszeru szo rossz megszolitast adhat.
// Az osszehasonlitas ekezet- es kisbetu-fuggetlen (nevek.js: hajtogat), ezert csak olyan betu lehet benne, ami ekezet-lehuzas utan
// a-z (tehat pl. ł, đ, ø nem): lengyel/szerb nevet ezek nelkul kell irni (Lukasz).
export const KERESZTNEVEK_LISTA = [
  // --- magyar noi nevek: gyakori ---
  'Katalin', 'Ágnes', 'Éva', 'Zsuzsanna', 'Mária', 'Erzsébet', 'Anna', 'Judit', 'Andrea', 'Ildikó', 'Edina', 'Krisztina', 'Szilvia', 'Tünde',
  'Mónika', 'Orsolya', 'Eszter', 'Réka', 'Nikoletta', 'Bernadett', 'Dóra', 'Fanni', 'Lilla', 'Petra', 'Viktória', 'Nóra', 'Gabriella',
  'Ilona', 'Margit', 'Julianna', 'Gyöngyi', 'Gyöngyvér', 'Piroska', 'Irén', 'Jolán', 'Gizella', 'Etelka', 'Ibolya', 'Vilma', 'Aranka',
  'Ilka', 'Lenke', 'Sarolta', 'Terézia', 'Teréz', 'Franciska', 'Hermina', 'Hedvig', 'Ida', 'Izabella', 'Gréta', 'Olga', 'Ottilia', 'Paula',
  'Berta', 'Cecília', 'Eugénia', 'Karolina', 'Lujza', 'Matild', 'Róza', 'Szidónia', 'Emília', 'Juliska', 'Jusztina', 'Kamilla', 'Klementina',
  'Margaréta', 'Veronka', 'Zsófia', 'Zsanett', 'Zsanna', 'Zsuzsa', 'Zita', 'Tímea', 'Szabina', 'Szandra', 'Renáta', 'Rita', 'Ramóna',
  'Patrícia', 'Noémi', 'Nikolett', 'Melinda', 'Marianna', 'Mariann', 'Marietta', 'Magdolna', 'Magda', 'Lívia', 'Lídia', 'Laura', 'Klaudia',
  'Kitti', 'Kinga', 'Klára', 'Katinka', 'Janka', 'Jázmin', 'Johanna', 'Júlia', 'Henrietta', 'Henriett', 'Hanna', 'Hajnalka', 'Gerda',
  'Flóra', 'Fruzsina', 'Emese', 'Emma', 'Enikő', 'Erika', 'Diána', 'Dorottya', 'Dorina', 'Dalma', 'Csilla', 'Csenge', 'Cintia', 'Boglárka',
  'Borbála', 'Bianka', 'Blanka', 'Bettina', 'Beatrix', 'Beáta', 'Barbara', 'Anikó', 'Anita', 'Anett', 'Alexandra', 'Adrienn', 'Adél',
  'Aliz', 'Alíz', 'Amália', 'Anasztázia', 'Annamária', 'Annabella', 'Anetta', 'Angéla', 'Angelika', 'Antónia', 'Arabella', 'Ágota',
  // --- magyar noi nevek: ritkabbak, ujabbak ---
  'Aida', 'Alexa', 'Alexia', 'Alina', 'Alma', 'Amanda', 'Amina', 'Angelina', 'Aurélia', 'Auróra', 'Adina', 'Adrienne', 'Anne', 'Anzelma',
  'Bella', 'Berill', 'Bernadette', 'Bíborka', 'Boróka', 'Brigitta', 'Celesztina', 'Debóra', 'Delila', 'Dorisz', 'Dorka', 'Dorothea', 'Edit',
  'Elektra', 'Eleonóra', 'Elvira', 'Ella', 'Eliza', 'Elizabet', 'Emőke', 'Erna', 'Ernesztina', 'Eufrozina', 'Evelin', 'Evelina', 'Eveline',
  'Evelyn', 'Fiona', 'Felícia', 'Fédra', 'Florencia', 'Gertrúd', 'Gina', 'Gloria', 'Hajna', 'Hanga', 'Helén', 'Helena', 'Helga', 'Hella',
  'Hilda', 'Hortenzia', 'Ilma', 'Imola', 'Inez', 'Ingrid', 'Irma', 'Irina', 'Írisz', 'Iringó', 'Izolda', 'Ivett', 'Ivetta', 'Ivonn',
  'Jasmin', 'Jasmine', 'Jolanta', 'Joanna', 'Julietta', 'Juliett', 'Kamélia', 'Karin', 'Karina', 'Karola', 'Katarina', 'Katrin', 'Kincső',
  'Kira', 'Kiara', 'Kornélia', 'Krisztiána', 'Kyra', 'Lara', 'Larissza', 'Lea', 'Léna', 'Lenka', 'Leona', 'Lia', 'Liana', 'Liliána', 'Lilien',
  'Linda', 'Liza', 'Lola', 'Lorena', 'Loretta', 'Lotta', 'Luca', 'Luna', 'Mara', 'Marcella', 'Márta', 'Martina', 'Mercédesz', 'Melánia',
  'Melitta', 'Mia', 'Mikaela', 'Milena', 'Mila', 'Minka', 'Mira', 'Mirabella', 'Miranda', 'Mirjam', 'Mirella', 'Mirtill', 'Nadin', 'Nadia',
  'Nadine', 'Natália', 'Natasa', 'Natasza', 'Nelli', 'Nikol', 'Nikolina', 'Nina', 'Olívia', 'Olimpia', 'Oxána', 'Pálma', 'Pamela', 'Panna',
  'Paulina', 'Perla', 'Pia', 'Polixéna', 'Rafaela', 'Rebeka', 'Regina', 'Rozália', 'Rozina', 'Rubina', 'Ruth', 'Sára', 'Sába', 'Szimonetta',
  'Szimona', 'Szonja', 'Sztella', 'Szelina', 'Szeréna', 'Stefánia', 'Stella', 'Tabita', 'Tamara', 'Tekla', 'Tessza', 'Tilda', 'Tiara',
  'Vanda', 'Vanessza', 'Vera', 'Veronika', 'Villő', 'Viola', 'Violetta', 'Virág', 'Vivien', 'Viviána', 'Valéria', 'Valentina', 'Verona',
  'Xénia', 'Zelma', 'Zoé', 'Zselyke', 'Zsazsa', 'Zsóka', 'Györgyi', 'Gabriela', 'Gizi', 'Hermina', 'Lenke', 'Magdaléna', 'Nefelejcs',
  'Abigél', 'Aletta', 'Alissza', 'Amarilla', 'Amira', 'Annika', 'Ariana', 'Arianna', 
  'Bernadin', 'Bruna', 'Cili', 'Denisa', 'Denise', 'Detti', 'Dzsenifer', 'Dzsesszika', 'Eleni', 'Elina',
  'Elmira', 'Emerencia', 'Fatime', 'Gemma', 'Gitta', 'Gréti', 'Jolánka', 'Jusztina',
  // --- becezett noi alakok ---
  'Zsófi', 'Zsuzsi', 'Kati', 'Évi', 'Ági', 'Bori', 'Ancsa', 'Niki', 'Dóri', 'Marcsi', 'Lili', 'Panni', 'Réni', 'Timi', 'Gabi', 'Kriszti',
  'Betti', 'Móni', 'Vivi', 'Szilvi', 'Kata', 'Katica', 'Kriszta', 'Bea', 'Bibi', 'Bogi', 'Böbe', 'Bözsi', 'Erzsi', 'Dorci', 'Dorcsi', 'Eszti',
  'Eni', 'Emi', 'Emcsi', 'Ibi', 'Ica', 'Ildi', 'Ili', 'Juci', 'Julcsi', 'Juli', 'Jutka', 'Kami', 'Klári', 'Lenci', 'Lizi', 'Lotti', 'Lujzi',
  'Manci', 'Margi', 'Mari', 'Marika', 'Mariska', 'Mici', 'Mimi', 'Nóri', 'Nusi', 'Orsi', 'Panka', 'Piri', 'Rozi', 'Sári', 'Szandi', 'Tündi',
  'Vali', 'Veri', 'Viki', 'Vikki', 'Zsani', 'Hajni', 'Livi', 'Patri', 'Barbi', 'Brigi', 'Hanni', 'Henni', 'Henci', 'Fruzsi', 'Flóri', 
  'Annus', 'Anci', 'Ágika', 'Zsófika', 'Cecil', 'Dia', 'Dina', 'Juliánna', 'Terka', 'Kitty', 'Lilike', 'Lizike', 'Marcsa', 'Szilvike', 'Tinka',
  'Pannika', 'Annuska', 'Anikó', 'Jusztí', 'Zsuzsika', 'Katika', 'Zita', 'Kitti',
  // --- kulfoldi noi nevek (angol, nemet, francia, olasz, spanyol, szlovak, cseh, lengyel, roman, szerb-horvat, orosz-ukran) ---
  'Jessica', 'Jessika', 'Jennifer', 'Jenny', 'Jenifer', 'Sophie', 'Sophia', 'Sofia', 'Sonja', 'Sonia', 'Sara', 'Sarah', 'Maria', 'Anastasia',
  'Natalia', 'Natalie', 'Natasha', 'Elena', 'Elisabeth', 'Elisa', 'Elise', 'Elsa', 'Esther', 'Eva', 'Julia', 'Lisa', 'Alice', 'Carla', 'Clara',
  'Claudia', 'Christina', 'Kristina', 'Kristin', 'Kristína', 'Caroline', 'Carmen', 'Catherine', 'Charlotte', 'Chiara', 'Cynthia', 'Daria',
  'Dalia', 'Daniela', 'Daniella', 'Diana', 'Dominika', 'Emily', 'Emilia', 'Estelle', 'Fabiola', 'Francesca', 'Franziska', 'Gabrielle', 'Giulia',
  'Giorgia', 'Greta', 'Heidi', 'Helene', 'Isabella', 'Isabelle', 'Isabel', 'Izabel', 'Izabela', 'Jacqueline', 'Jaqueline', 'Jana', 'Jasmina',
  'Jelena', 'Jitka', 'Jovana', 'Katarína', 'Katharina', 'Katja', 'Kateřina', 'Lena', 'Lilian', 'Lucie', 'Lucy', 'Lucia', 'Lucija', 'Ludmilla',
  'Maja', 'Manuela', 'Margareta', 'Margarita', 'Marija', 'Marie', 'Marlene', 'Martha', 'Michaela', 'Michelle', 'Miriam', 'Mona', 'Nicole',
  'Nikoleta', 'Oksana', 'Olivia', 'Patricia', 'Petronella', 'Pavla', 'Rachel', 'Rebecca', 'Renata', 'Roberta', 'Romina', 'Rosa', 'Roxana',
  'Sabrina', 'Sabina', 'Samantha', 'Sandra', 'Selina', 'Silvia', 'Simona', 'Stephanie', 'Susanna', 'Svetlana', 'Tatiana', 'Tatjana', 'Tereza',
  'Tiffany', 'Tina', 'Veronica', 'Victoria', 'Viktorija', 'Vlasta', 'Yvette', 'Yvonne', 'Zuzana', 'Zuzanna', 'Zdenka', 'Zlata', 'Zorica',
  'Agnieszka', 'Magdalena', 'Malgorzata', 'Katarzyna', 'Aleksandra', 'Ewa', 'Alena', 'Marta', 'Hana', 'Ivana', 'Ivona', 'Iva', 'Jarmila',
  'Milica', 'Ana', 'Anamaria', 'Dragana', 'Tijana', 'Snezana', 'Andreea', 'Ioana', 'Cristina', 'Mihaela', 'Adriana', 'Bianca', 'Raluca',
  'Oana', 'Ramona', 'Corina', 'Larisa', 'Madalina', 'Alexandrina', 'Antonella', 'Antonia', 'Arina', 'Asztrid', 'Audrey', 'Aurora', 'Ava',
  'Birgit', 'Bridget', 'Dorothea', 'Elke', 'Erika', 'Federica', 'Gudrun', 'Gisela', 'Heike', 'Ines', 'Ingeborg', 'Irene', 'Jolanda', 'Karolin',
  'Ksenia', 'Larissa', 'Lidia', 'Liliana', 'Lorraine', 'Louisa', 'Margot', 'Marina', 'Marlen', 'Melissa', 'Mirela', 'Nathalie', 'Nikola',
  'Olga', 'Paola', 'Paloma', 'Pilar', 'Rosalia', 'Sandrine', 'Sylvia', 'Tamar', 'Teodora', 'Ulrike', 'Ursula', 'Urszula', 'Valentina',
  'Valerie', 'Vanessa', 'Vera', 'Veronique', 'Viktoria', 'Wilhelmina', 'Yulia', 'Yana', 'Zoe', 'Zsofia', 'Dasa', 'Dagmar', 'Eliska', 'Ilse',
  'Maryna', 'Halyna', 'Iryna', 'Olena', 'Tetiana', 'Liudmila', 'Elizaveta', 'Ekaterina', 'Irina', 'Galina', 'Nadezda', 'Natalija', 'Anastasija',
  // --- arab, azsiai es egyeb nevek ---
  'Aisha', 'Fatima', 'Leila', 'Layla', 'Yasmin', 'Yasmine', 'Nour', 'Noor', 'Salma', 'Zahra', 'Samira', 'Rania', 'Hanan', 'Mariam', 'Amal',
  'Mei', 'Yuki', 'Sakura', 'Linh', 'Mai', 'Hoa', 'Lan', 'Trang', 'Huong', 'Thuy', 'Ngoc', 'Yuna', 'Aiko', 'Mina', 'Jia', 'Priya', 'Anjali',
  'Aylin', 'Elif', 'Ayse', 'Fatma', 'Zeynep', 'Leyla', 'Shirin', 'Dina',
  // --- magyar ferfi nevek: gyakori ---
  'István', 'János', 'Gábor', 'László', 'Péter', 'Zoltán', 'Attila', 'Tamás', 'Ferenc', 'Balázs', 'Ádám', 'Dávid', 'Máté', 'Márton',
  'József', 'Sándor', 'Lajos', 'Imre', 'Béla', 'Gyula', 'Pál', 'Mihály', 'Károly', 'Antal', 'Jenő', 'Rezső', 'Ödön', 'Kálmán', 'Dezső',
  'Ernő', 'Gusztáv', 'Géza', 'Elemér', 'Aladár', 'Tivadar', 'Vilmos', 'Vince', 'Ottó', 'Oszkár', 'Gedeon', 'Bertalan', 'Dénes', 'Endre',
  'Ervin', 'Ede', 'Győző', 'Henrik', 'Iván', 'Kornél', 'Mór', 'Nándor', 'Sebestyén', 'Szilárd', 'Tódor', 'Vendel', 'Zsigmond', 'Ignác',
  'Lénárd', 'Pongrác', 'Miksa', 'Gáspár', 'Menyhért', 'Boldizsár', 'Fülöp', 'Frigyes', 'Rudolf', 'Emil', 'Jónás', 'Mózes', 'Ábrahám',
  'Izsák', 'Sámuel', 'Samu', 'Aurél', 'Konrád', 'Leó', 'Albert', 'Alfréd', 'Artúr', 'Árpád', 'Álmos', 'Előd', 'Etele', 'Zsolt', 'Csaba',
  'Norbert', 'Roland', 'Richárd', 'Róbert', 'Viktor', 'Krisztián', 'Tibor', 'György', 'Miklós', 'Bálint', 'Benedek', 'Bence', 'Levente',
  'Zalán', 'Milán', 'Marcell', 'Dominik', 'Márk', 'Patrik', 'Kristóf', 'Gergely', 'Gergő', 'Szabolcs', 'Barnabás', 'Bendegúz', 'Botond',
  'Csanád', 'Csongor', 'Dorián', 'Hunor', 'Koppány', 'Kolos', 'Lehel', 'Lóránt', 'Lóránd', 'Lőrinc', 'Mátyás', 'Noel', 'Olivér', 'Soma',
  'Zétény', 'Zsombor', 'Áron', 'Ábel', 'Ákos', 'Ágoston', 'Adorján', 'Adrián', 'András', 'Andor', 'Anton', 'Ármin', 'Arnold', 'Bazil', 'Bertold',
  'Bonifác', 'Bódog', 'Bulcsú', 'Bernát', 'Cirill', 'Cézár', 'Damján', 'Domonkos', 'Dömötör', 'Döme', 'Egyed', 'Elek', 'Emánuel', 'Emilián',
  'Erik', 'Félix', 'Ferdinánd', 'Flórián', 'Gellért', 'Gilbert', 'Huba', 'Hugó', 'Ivó', 'Jákob', 'Jeromos', 'Jonatán', 'Jordán',
  'Kamill', 'Kázmér', 'Keve', 'Kilián', 'Kende', 'Lázár', 'Leonárd', 'Leopold', 'Medárd', 'Mirkó', 'Móric', 'Nátán', 'Nátánael', 'Nárcisz',
  'Nimród', 'Oszvald', 'Radó', 'Rómeó', 'Román', 'Rókus', 'Rajmund', 'Rikárd', 'Sámson', 'Szebasztián', 'Szilveszter', 'Szervác',
  'Szeverin', 'Szaniszló', 'Tádé', 'Teodor', 'Tihamér', 'Tihomér', 'Titusz', 'Tobiás', 'Timót', 'Timon', 'Urbán', 'Valér', 'Vazul', 'Vencel',
  'Vid', 'Vitális', 'Zénó', 'Zoárd', 'Zakariás', 'Zachariás', 'Zente', 'Ajtony', 'Amadé', 'Anzelm', 'Benő', 'Borisz', 'Dárió', 'Fedor',
  'Noé', 'Lotár', 'Lénárd', 'Marián', 'Maxim', 'Maximilián', 'Mihály', 'Oszkár', 'Pius', 'Piusz', 'Tódor',
  'Jusztin', 'Lőrinc', 
  // --- becezett ferfi alakok ---
  'Feri', 'Gyuri', 'Józsi', 'Jani', 'Jancsi', 'Laci', 'Lackó', 'Misi', 'Miki', 'Pali', 'Peti', 'Pisti', 'Sanyi', 'Tomi', 'Zoli', 'Bandi', 'Berci',
  'Csabi', 'Dani', 'Gyuszi', 'Imi', 'Krisz', 'Máti', 'Marci', 'Matyi', 'Norbi', 'Robi', 'Szabi', 'Tibi', 'Zsolti', 'Ricsi', 'Richi', 'Béci',
  'Barni', 'Boti', 'Árpi', 'Dezsi', 'Gazsi', 'Gida', 'Gerzson', 'Andris', 'Andi', 'Öcsi', 'Samu', 'Zsiga', 'Pityu', 'Jóska', 'Lali', 'Frici',
  'Gabi', 'Ottó', 'Géza', 'Ferkó', 'Kálmi', 'Guszti', 'Nandi', 'Nándi',
  // --- kulfoldi ferfi nevek (angol, nemet, francia, olasz, spanyol, szlovak, cseh, lengyel, roman, szerb-horvat, orosz-ukran, arab) ---
  'Daniel', 'Michael', 'Oliver', 'Alexander', 'Alex', 'Adam', 'David', 'Peter', 'Paul', 'Mark', 'Marcus', 'Martin', 'Max', 'Ben', 'Benjamin',
  'Tom', 'Thomas', 'Tobias', 'Patrick', 'Robert', 'Richard', 'Kevin', 'Brian', 'Bryan', 'Dennis', 'Denis', 'Lukas', 'Lukáš', 'Luca', 'Liam',
  'Leon', 'Louis', 'Lucas', 'Jack', 'James', 'John', 'Jason', 'Jonathan', 'Joseph', 'George', 'Harry', 'Henry', 'William', 'Wilhelm',
  'Wolfgang', 'Steven', 'Stephen', 'Stefan', 'Stefano', 'Simone', 'Sebastian', 'Samuel', 'Raphael', 'Ralf', 'Raul', 'Ronald',
  'Noah', 'Nicolas', 'Nikolaus', 'Nikolai', 'Nikola', 'Norman', 'Philip', 'Philipp', 'Pierre', 'Michel', 'Philippe', 'Jacques', 'Jean', 'Francois',
  'Felix', 'Fabian', 'Fabio', 'Fabrizio', 'Filip', 'Filippo', 'Francisco', 'Franz', 'Frederik', 'Gabriel', 'Gabriele', 'Giovanni', 'Giuseppe',
  'Gregor', 'Gustav', 'Hans', 'Helmut', 'Hubert', 'Hugo', 'Ian', 'Igor', 'Ivan', 'Jakub', 'Jan', 'Josef', 'Jozef', 'Karl', 'Klaus', 'Kurt',
  'Konstantin', 'Christian', 'Christopher', 'Chris', 'Christoph', 'Cristian', 'Carlos', 'Carlo', 'Claudio', 'Damir', 'Danilo', 'Darius', 'Dario',
  'Dejan', 'Diego', 'Dino', 'Dragan', 'Dusan', 'Dušan', 'Eduard', 'Edward', 'Edgar', 'Emanuel', 'Emmanuel', 'Enrico', 'Enzo', 'Eric', 'Ernest',
  'Eugen', 'Alan', 'Albin', 'Alejandro', 'Alessandro', 'Alexey', 'Andrej', 'Andrew', 'Andrey', 'Andrei', 'Andreas', 'Anthony', 'Antonio',
  'Aron', 'Arthur', 'Axel', 'Boris', 'Bruno', 'Goran', 'Ivo', 'Jürgen', 'Juraj', 'Ján', 'Ladislav', 'Luigi', 'Manuel', 'Marcin', 'Marek',
  'Mario', 'Marko', 'Marco', 'Marcel', 'Marian', 'Matthias', 'Matej', 'Mateusz', 'Matei', 'Michal', 'Miguel', 'Mihai', 'Milan', 'Milos', 'Miloš',
  'Miroslav', 'Mladen', 'Nemanja', 'Bojan', 'Branko', 'Predrag', 'Slobodan', 'Aleksandar', 'Vladimir', 'Vladimír', 'Vlad', 'Vladislav', 'Zoran',
  'Pablo', 'Paolo', 'Pavel', 'Pavol', 'Petr', 'Pietro', 'Rastislav', 'Ricardo', 'Roberto', 'Rodrigo', 'Sergio', 'Sergey', 'Sergej', 'Teodor',
  'Tomas', 'Tomáš', 'Tomasz', 'Lukasz', 'Pawel', 'Piotr', 'Krzysztof', 'Andrzej', 'Michal', 'Wojciech', 'Vasile', 'Alexandru', 'Cosmin', 'Florin',
  'Sorin', 'Bogdan', 'Razvan', 'Gheorghe', 'Constantin', 'Lucian', 'Marius', 'Ovidiu', 'Radu', 'Catalin', 'Mircea', 'Nicolae', 'Octavian',
  'Ionut', 'Stefan', 'Štefan', 'Dimitri', 'Dmitry', 'Dmitrij', 'Oleg', 'Olaf', 'Ahmed', 'Ali', 'Hassan', 'Hussein', 'Karim', 'Khaled', 'Mahmoud',
  'Mohamed', 'Mohammad', 'Muhammad', 'Mustafa', 'Omar', 'Rami', 'Sami', 'Samir', 'Tarek', 'Youssef', 'Yusuf', 'Ibrahim', 'Hamza', 'Amir',
  'Hiroshi', 'Kenji', 'Takeshi', 'Brandon', 'Dylan', 'Ethan', 'Evan', 'Gabriel', 'Isaac', 'Jayden', 'Jonas', 'Julian', 'Justin', 'Kilian',
  'Lorenz', 'Ludwig', 'Mathias', 'Maurice', 'Moritz', 'Niklas', 'Noel', 'Oscar', 'Otto', 'Rafael', 'Rene', 'Theo', 'Tim', 'Timo', 'Tobi',
  'Valentin', 'Victor', 'Vincent', 'Xavier', 'Xavér', 'Zachary', 'Zeno', 'Andre', 'Anatol', 'Anatolij', 'Arkadij', 'Artem', 'Bohdan', 'Denys',
  'Dmytro', 'Mykola', 'Oleksandr', 'Roman', 'Serhij', 'Taras', 'Viktor', 'Volodymyr', 'Yaroslav', 'Egor', 'Evgenij', 'Kirill', 'Maksim', 'Nikita',
  'Pavlo', 'Sasha', 'Sergei', 'Vadim', 'Vitalij', 'Zdenek',
];
