// Oxigenterapia - booking-to-show uzenetlanc (MOSAIC_booking_to_show_lifecycle_2026-10-07.pdf, 5. fejezet). A szoveg a dokumentum szerint, szo szerint.
// A katalogus-formatum leirasa: netlify/lib/lifecycle/katalog/SEMA.md. Az arak / akciok / honapnevek NEM kerulnek a szovegbe (lasd: megjegyzesek).
export default {
  uzletag: 'oxygen',
  uzenetek: [
    {
      id: 'OX-SMS-01', csatorna: 'sms', mikor: { tipus: 't0' },
      szoveg: 'Szia {keresztnév}! Megvan az időpontod: {dátum} {időpont}, {szolgáltatás}. MOSAIC, 1023 Budapest, Bécsi út 2. Részletek/módosítás: {foglalás_részletei_link}. Várunk!',
    },
    {
      id: 'OX-EMAIL-01', csatorna: 'email', mikor: { tipus: 't0' }, szegmensek: ['konzultacio', 'elso'],
      targy: 'Időpontod rögzítve – erre számíthatsz az első oxigénterápián',
      elotag: 'Hajkamerás állapotfelméréssel indulunk, privát kezelőhelyiségben, személyre szabva.',
      torzs: [
        'Szia {keresztnév}!',
        'Köszönjük a foglalásodat, várunk szeretettel a Mosaicban.',
        'Az időpontod:',
        { doboz: ['{szolgáltatás}', '{dátum}, {időpont}', 'Helyszín: 1023 Budapest, Bécsi út 2.'] },
        'Az első alkalom egyik legfontosabb része, hogy pontosan felmérjük a fejbőröd és a hajad jelenlegi állapotát, és ne általános tanácsok alapján induljunk el.',
        { cim: 'Először megnézzük, honnan indulunk' },
        'Hajkamerával részletesen megvizsgáljuk a fejbőröd állapotát, a hajhagymák környezetét, a hajszálakat és azokat a jeleket, amelyek szabad szemmel sokszor még alig láthatók.',
        { kep: { src: 'oxygen/hajkamera-vizsgalat.jpg', alt: 'A vendég a kezelőágyon fekszik, a kezelő a fejbőrt vizsgálja, a tableten a hajkamera képe látszik', felirat: 'A hajkamerás vizsgálat: a tableten látszik a fejbőr képe', szelesseg: 440 } },
        'Ennek két fontos szerepe van.',
        'Egyrészt ez alapján tudjuk személyre szabni az oxigénterápiás kezelést és a felhasznált Oxygeni hatóanyagokat a te fejbőröd aktuális problémájához.',
        'Másrészt lesz egy pontos kiindulási állapotunk. Így akkor is objektíven tudjuk követni a változást, ha te az első néhány alkalom után még nem érzed vagy látod egyértelműen: a hajkamera sokszor hamarabb megmutatja a fejbőrön és a hajhagymák környezetében elinduló változásokat.',
        { cim: 'Nem ugyanazt a kezelést kapja mindenki' },
        'A kezelés során orvosi tisztaságú oxigén segítségével juttatjuk be a kiválasztott hatóanyagokat a fejbőr mélyebb rétegeibe. Az Oxygeni kezelési rendszere éppen azért épül állapotfelmérésre, mert más kombináció lehet indokolt például hajhullásnál, érzékeny vagy gyulladt fejbőrnél, korpásodásnál vagy hajritkulásnál.',
        {
          kiemelt: {
            cim: 'Miért működik?',
            vezeto: 'Mert pontosan ott hat, ahol a probléma van: a hajhagymák mélyén, a fejbőrben.',
            szoveg: [
              'Nem felszíni kezelés. Nem kozmetikai kezelés, nem hajmosás, nem tisztítás. A magas tisztaságú oxigénnel vitaminokat juttatunk a fejbőrbe, vagyis belülről tápláljuk a hajhagymákat, oda, ahol semmilyen más kezelés nem jut el.',
              'Az oxigénterápia valójában semmi mást nem tesz, mint helyreállítja a hajhagymák normális működését. **Ezért működik.**',
            ],
            kep: { src: 'oxygen/miert-mukodik.jpg', alt: 'Szemléltető kép: a kezelő az oxigént a fejbőrre juttatja; a kiemelt kör a hajhagymák táplálását mutatja', szelesseg: 280 },
          },
        },
        'Az Oxygeni statisztikája szerint a világszerte elvégzett kétmillió kezelésből 95%-nál pozitív változás történt.',
        { cim: 'Maga a kezelés nyugodt és fájdalommentes élmény' },
        'Nálunk nem egy nyitott fodrásztérben történik a kezelés.',
        'Külön, privát kezelőhelyiségben leszel, fekvő helyzetben, így az alkalom közben valóban ki tudsz kapcsolni. Nem ül melletted más vendég, nincs körülötted folyamatos jövés-menés.',
        { kep: { src: 'oxygen/kezeles-kozben.jpg', alt: 'Privát kezelőhelyiség a MOSAIC-ban: a vendég fekszik, a kezelő a fejbőrén dolgozik', felirat: 'Privát kezelőhelyiség: csak te és a kezelőd vagytok bent' } },
        'A kezelés kíméletes, nem jár tűvel vagy fájdalmas beavatkozással.',
        'A célunk nem egyszerűen az, hogy „csináljunk egy kezelést", hanem hogy a te fejbőröd állapotához igazítva a lehető legjobb eredményt érjük el.',
        'Egy kérésünk van: kérjük, tiszta, száraz hajjal érkezz.',
        'Foglalás részletei / módosítás:',
        { gomb: { felirat: 'Foglalás megtekintése / módosítása', link: '{foglalás_részletei_link}' } },
        'Találkozunk hamarosan!',
      ],
    },
    {
      id: 'OX-EMAIL-02', csatorna: 'email', mikor: { tipus: 'tartalom', utan_napok: 2, min_lead_nap: 5 }, sorrend: 1, szegmensek: ['konzultacio', 'elso'],
      targy: 'Mit fogunk megnézni a hajkamerával?',
      elotag: 'Az első alkalom célja: kevesebb találgatás, több konkrétum.',
      torzs: [
        'Szia {keresztnév}!',
        { kep: { src: 'oxygen/hajkamera-nezet.jpg', alt: 'Szemléltető kép: a hajkamera erősen nagyított képe a fejbőrről, a hajhagymákról és a hajszálakról', felirat: 'Szemléltető kép: a hajkamera nagyított képe a fejbőrről' } },
        'Sokan azért érkeznek bizonytalanul, mert már rengeteg általános tanácsot hallottak a hajukról. Nálunk pont ezt szeretnénk elkerülni.',
        'A hajkamera arra jó, hogy ne csak találgassunk. Megnézzük a fejbőr felszínét és azokat a jeleket, amelyek a személyre szabott kezelés megtervezéséhez fontosak lehetnek. Utána átbeszéljük veled, mit látunk és mi az, amit reálisan érdemes csinálni.',
        'Az OXYGENI termékeket sem sablonból választjuk: a kezelési tervhez igazítjuk őket.',
        { kep: { src: 'oxygen/kezeles-kozben.jpg', alt: 'Oxigénterápiás kezelés a MOSAIC kezelőszobájában: a kezelő a fekvő vendég fejbőrén dolgozik', felirat: 'Oxigénterápiás kezelés közben' } },
        'A célunk, hogy a kezelés nálad a lehető leghatásosabb legyen, ezért úgy állítjuk össze, hogy nálad érje el a legnagyobb eredményt.',
        'Ha szeretnéd előre megnézni, milyen egy kezelés:',
        { video: { src: 'oxygen/video-kezeles.jpg', alt: 'A kezelő a MOSAIC kezelőszobájában a fekvő vendég fejbőrével foglalkozik; lejátszás gomb a videó előképén', felirat: 'Így zajlik egy oxigénterápiás kezelés', link: '{videó_link}' } },
        { gomb: { felirat: 'Megnézem a videót', link: '{videó_link}' } },
        'Találkozunk {dátum_ragos}.',
      ],
    },
    {
      id: 'OX-EMAIL-03', csatorna: 'email', mikor: { tipus: 'tartalom', elott_napok: 6, min_lead_nap: 10 }, sorrend: 2, szegmensek: ['konzultacio', 'elso'],
      targy: 'Mikor látható az oxigénterápia eredménye?',
      elotag: 'Reális elvárások: mikor jönnek az első változások, és mikor érdemes megítélni az eredményt.',
      torzs: [
        'Szia {keresztnév}!',
        'Az első kezelésed előtt szeretnénk egy fontos dolgot tisztázni, mert ez segít reális elvárásokkal érkezni.',
        { cim: 'Az oxigénterápia nem egyetlen „csodakezelés"' },
        'A haj és a fejbőr állapota hosszabb idő alatt alakul ki, ezért a regeneráció is egy folyamat.',
        'Sok vendégünknél már 1–2 alkalom után megjelennek az első pozitív változások: nyugodtabbnak érzik a fejbőrüket, csökkenhet a hajhullás, javulhat a haj minősége vagy egyszerűen egészségesebbnek érzik a fejbőrt.',
        'A látványosabb változásokhoz azonban jellemzően több alkalom szükséges. 5–6 kezelés után már sokkal jobban megítélhető, hogyan reagál a fejbőröd és milyen eredményt értünk el.',
        { kepek: [
          { src: 'oxygen/eredmeny-hajhullas.jpg', alt: 'Hajhullás: a fejtető felülnézetben a kezelések előtt (bal oldalt) és után (jobb oldalt)', felirat: 'Hajhullás: előtte és utána' },
          { src: 'oxygen/eredmeny-korpa.jpg', alt: 'Korpás fejbőr: a tarkó a kezelések előtt (bal oldalt) és után (jobb oldalt)', felirat: 'Korpás fejbőr: előtte és utána' },
        ] },
        'Ezért nem előre, sablonból mondjuk meg, hogy neked pontosan hány kezelésre lesz szükséged.',
        { cim: 'A hajkamera nem csak az első vizsgálatnál fontos' },
        'Az első alkalommal rögzítjük a kiinduló állapotot.',
        'A következő vizsgálatoknál ugyanazokat a területeket újra meg tudjuk nézni nagyításban. Ez azért különösen hasznos, mert a fejbőrön és a hajhagymák környezetében már akkor is elindulhat javulás, amikor azt a tükörben még nehéz észrevenni.',
        'Így nem érzés alapján döntjük el, hogy működik-e a kezelés: össze tudjuk hasonlítani a kiinduló és az aktuális állapotot.',
        { cim: 'A következő kezelést mindig az eredményekhez igazítjuk' },
        'Nem egy előre rögzített kezelési sablont ismétlünk.',
        'Megnézzük, hogyan reagált a fejbőröd, és ennek megfelelően választjuk ki a következő alkalomhoz szükséges Oxygeni termékeket és hatóanyagokat.',
        'Az Oxygeni professzionális kezeléseinél a hatóanyagokat orvosi tisztaságú oxigénnel, speciális nyomástechnikával juttatják a fejbőr mélyebb rétegeibe; a kezelést kizárólag képzett Oxygeni-partnerek végezhetik.',
        { cim: 'Az otthoni rutin ugyanúgy része az eredménynek' },
        'Két kezelés között sem mindegy, mi kerül a fejbőrödre.',
        'Ezért, ha kúrában folytatod a kezelést, Oxygeni sampont is adunk ajándékba, hogy otthon is olyan hajápolási rutint tudj kialakítani, amely illeszkedik a kezeléshez.',
        { kep: { src: 'oxygen/sampon.jpg', alt: 'Az ajándék 1 literes Oxygeni Hair Loss sampon', felirat: 'Az ajándék Oxygeni sampon', szelesseg: 300 } },
        'Az Oxygeni termékek természetes eredetű hatóanyagokra épülnek; a márka termékei vegánok, mesterséges színezék és mesterséges parfüm nélkül készülnek.',
        'A kezelések között ezért érdemes fokozatosan áttérni a számunkra javasolt természetesebb, fejbőrbarát ápolásra – ebben természetesen segítünk, nem kell magadnak kitalálnod, mire van szükséged.',
        { cim: 'Amit tőlünk várhatsz' },
        'Nem ígérünk mindenkinek ugyanannyi idő alatt ugyanakkora eredményt.',
        'Azt viszont igen, hogy mérjük a kiindulási állapotodat, követjük a változást, és minden alkalommal ahhoz igazítjuk a kezelést, amit a fejbőröd ténylegesen mutat.',
        'Így tudjuk a legtöbbet kihozni az oxigénterápiából.',
        'A te időpontod:',
        { doboz: ['{szolgáltatás}', '{dátum}, {időpont}'] },
        'Várunk szeretettel!',
      ],
    },
    {
      id: 'OX-SMS-02', csatorna: 'sms', mikor: { tipus: 't72' },
      szoveg: 'Szia {keresztnév}! 3 nap múlva {időpont}-kor várunk {szolgáltatás}-ra. Ha jössz: {megerősítés_link}. Ha változott valami, itt tudod áttenni: {módosítás_link}. Kérjük, tiszta, száraz hajjal érkezz. MOSAIC',
    },
    {
      id: 'OX-EMAIL-04', csatorna: 'email', mikor: { tipus: 't72' }, szegmensek: ['konzultacio', 'elso'],
      targy: 'Már csak ennyit kérünk az időpontod előtt',
      elotag: 'Tiszta, száraz haj - és minden mást együtt megnézünk.',
      torzs: [
        'Szia {keresztnév}!',
        'Már közel van az időpontod:',
        { doboz: ['{szolgáltatás}', '{dátum}, {időpont}'] },
        'Ezért csak a gyakorlati rész:',
        { lista: [
          'tiszta, száraz hajjal érkezz',
          'tervezz {várható_időtartam} időt',
          'a címed: 1023 Budapest, Bécsi út 2.',
          'ha az állapotfelmérés előtt bármi fontos új információ van, amit szeretnél elmondani a kezelőnek, nyugodtan írd össze magadnak.',
        ] },
        { kep: { src: 'oxygen/kezeles-kozben.jpg', alt: 'Oxigénterápiás kezelés a MOSAIC kezelőszobájában: a kezelő a fekvő vendég fejbőrén dolgozik', felirat: 'Így zajlik az oxigénterápiás kezelés' } },
        'Ha közbejött valami, itt tudod áttenni:',
        { gomb: { felirat: 'Itt tudom áttenni', link: '{módosítás_link}' } },
        'Várunk,',
      ],
    },
    {
      id: 'OX-SMS-03', csatorna: 'sms', mikor: { tipus: 't24' },
      szoveg: 'Szia {keresztnév}! Holnap {időpont}-kor várunk a MOSAIC-ban, 1023 Budapest, Bécsi út 2. Kérjük, tiszta, száraz hajjal érkezz, és tervezz {várható_időtartam} időt. Várunk!',
    },
  ],
  megjegyzesek: [
    'Ár/akció: az "Ajánlat- és forrászár" blokk fix összegei (konzultáció, kezelés, Arc + Haj) és a "Júniusban 10%" / 50%-os konzultációs kedvezmény NEM került át; az üzenetek dokumentum-szövege egyébként sem tartalmaz árat, így nem maradt ki üzenetsor, és {aktuális_ár} / {aktuális_ajánlat} sor sincs (az ár csak aktuális bookingadatból jöhet, a júniusi promóciót tilos továbbvinni).',
    'OX-EMAIL-03: a "PLAN-D-ben rögzített jelenlegi szolgáltatási logika..." belső hivatkozás az ügyfél felé így szól: "A jelenlegi szolgáltatási logika jellemzően 5-10 alkalmas kúrával és 1-2 hetes ritmussal számol..." (a "PLAN-D-ben rögzített" kifejezés kimaradt; az 5-10 alkalom / 1-2 hét a dokumentum szerint marad, nem ár és nem százalék).',
    'Gyógyulási garancia / diagnózis: a dokumentum elve szerint nem adtunk hozzá ilyen állítást; a szövegek a dokumentum eredeti mondatai.',
    'PDF-tördelési hibák javítva: a sortörések összefűzve (OX-SMS-01..03, OX-EMAIL-01..04, OX-CALL-01).',
    '"Találkozunk {dátum}-án." (OX-EMAIL-02) -> "Találkozunk {dátum_ragos}." (a ragozást a motor végzi).',
    'Önálló soros linkek gombbá alakítva, a bevezető mondat külön bekezdés: OX-EMAIL-01 (foglalás részletei / módosítás), OX-EMAIL-02 ({videó_link}), OX-EMAIL-04 ({módosítás_link}); a gomb-feliratok saját javaslatok ("Foglalás megtekintése / módosítása", "Megnézem a videót", "Itt tudom áttenni").',
    'Szegmensek: OX-EMAIL-01..04 és OX-CALL-01 csak konzultacio/elso (a doc: "új vendég", "konzultáció / első kezelés"). Az SMS-ek (OX-SMS-01/02/03) szegmens-megkötés nélkül minden vendégnek mennek: az 5.1 C. pont (visszatérő kúravendég) szerint ők is kapnak T0 + T-72/T-24 üzenetet, bár az 5.2 táblázat a T-72 / T-24 sorban "új vendéget" ír.',
    'Időzítés: "T+1..3 nap" -> OX-EMAIL-02 utan_napok: 2 (min_lead_nap 5, sorrend 1); "T-7..5 nap" -> OX-EMAIL-03 elott_napok: 6 (min_lead_nap 10, sorrend 2); OX-CALL-01 "T-24..48 Telefon" -> elott_ora: 48.',
    'OX-EMAIL-04: a doc "csak ha a prep még nem ment ki e-mailben" feltétele a formátumban nem fejezhető ki (a T0 e-mail is kéri a tiszta, száraz hajat); a katalógusban t72, csak konzultacio/elso; a duplikálás-szűrést a motor döntse el. A felsorolás pontosvesszői (tördelés) elmaradtak.',
    'OX-EMAIL-01 nem kapott surgos_kiegeszites blokkot: a dokumentum nem ír elő ilyet, és a kritikus előkészület (tiszta, száraz haj, cím) már benne van a T0 szövegben.',
    'OX-CALL-01: a dokumentumban nincs tárgy-sor; a "Oxigénterápia - hívandó vendég" tárgy a headspa minta (HS-CALL-01) alapján készült.',
    'OX-SMS-03 / OX-EMAIL-04: a {várható_időtartam} opcionális helyőrző; ismeretlen értéknél az e-mail felsorolás-sora kimarad, az SMS-03 viszont egy mondaton belül tartalmazza ("...és tervezz {várható_időtartam} időt.") - a motor SMS-ben csak a mondatrészt hagyja el, ne az egész üzenetet.',
  ],
};
