// Valodi Google-velemenyek (SZO SZERINTI, valogatott), az e-mail-sablonok `{ velemeny: '<id>' }` blokkjaihoz. NE modositsd a szoveget: csak az oldalon / a Trustindex-widgetben
// (Google) megjeleno velemeny kerulhet ide, valtoztatas nelkul. forras: ahol a szoveg megtalalhato (a katalogus-teszt a foglalas/*.html forrasokat egyezteti).
// A "datum" a Google-velemeny kelte (a widgetbol); a PMU-velemenyeknek az oldalon nincs datuma.
// A velemeny `uzletag` mezoje: melyik uzletag leveleiben szerepelhet. 'altalanos' = a szalonrol / a csapatrol / a helyrol szolo, kezelestol fuggetlen velemeny: barmelyik uzletag levelebe mehet
// (a lezeres / oxigenes kezelesrol szolo velemeny a Trustindex-widgetben nincs; ugyanaz a Google-widget az egesz szalone).
export const VELEMENYEK = Object.freeze({
  'pmu-gloria': { uzletag: 'pmu', nev: "Glória Dénes", datum: "", szoveg: "Szemöldöktetováláson voltam, egyszerűen hibátlan! A szalon gyönyörű, Melli kedves, a munkája páratlan!", forras: "foglalas/sminktetovalas-budapest.html" },
  'pmu-diana': { uzletag: 'pmu', nev: "Diana Ujszászi", datum: "", szoveg: "Melitta mindig tökéletesre varázsolja a szempilláimat. ❤️ Profi és megbízható szakember, akire bátran rábíztam a szemöldököm tetoválását is. A végeredmény gyönyörű lett, pontosan olyan, amilyet szerettem volna. Nagyon hálás vagyok neki, és szívből ajánlom mindenkinek!", forras: "foglalas/sminktetovalas-budapest.html" },
  'pmu-mirtill': { uzletag: 'pmu', nev: "Mirtill Bassa", datum: "", szoveg: "Fontos szempont volt, hogy természetes legyen – és nagyon elégedett vagyok a végeredménnyel!", forras: "foglalas/sminktetovalas-budapest.html" },
  'pmu-claudia': { uzletag: 'pmu', nev: "Claudia Tóth", datum: "", szoveg: "Melitta amellett, hogy nagyszerű szakember, egy nagyon kedves ember is. Imádom a szemöldököm és a szám, amit ő tetovált nekem. ☺️❤️", forras: "foglalas/sminktetovalas-budapest.html" },
  'pmu-melitta-farkas': { uzletag: 'pmu', nev: "Melitta Farkas", datum: "", szoveg: "Hálás vagyok, hogy Melitta személyében megismerhettem egy profi sminktetováló szakembert ❤️ Odafigyeléssel, precizitással dolgozik. Imádom a számat, amit varázsolt nekem. Bátran ajánlom mindenkinek! A szemöldököm javítását sem bízom másra – biztosan ő fogja csinálni azt is. Köszönöm, Melitta! ❤️", forras: "foglalas/sminktetovalas-budapest.html" },
  'pmu-alexandra': { uzletag: 'pmu', nev: "Alexandra Fejérpataky", datum: "", szoveg: "Melitta nagyon kedves és türelmes, igazi profi! A szalon is gyönyörű! ❤️", forras: "foglalas/sminktetovalas-budapest.html" },
  'hs-anett': { uzletag: 'headspa', nev: "Anett Soós", datum: "2026.09.29.", szoveg: "Isteni volt! Nagyon kedves mindenki, tiszta, szép a környezet. Olyan volt mint egy több órás pihentető alvás.", forras: "Trustindex / Google" },
  'hs-melinda': { uzletag: 'headspa', nev: "Szvitek Melinda", datum: "2026.08.19.", szoveg: "Nagyon jó élmény. Annyira ellazultam, hogy még órákkal késöbb is alig tértem magamhoz.", forras: "Trustindex / Google" },
  'hs-nikoletta': { uzletag: 'headspa', nev: "Nikoletta Dóráné Kiss", datum: "2026.09.21.", szoveg: "Nagyon kellemes relaxáló élmény volt. Tükörbe nézve megfiatalodtam. Köszönöm Dórinak a kezelést", forras: "Trustindex / Google" },
  'hs-greta': { uzletag: 'headspa', nev: "Gréta Molnár", datum: "2026.08.11.", szoveg: "Receptre kellene feliratni a kezelést! Zseniális volt!", forras: "Trustindex / Google" },
  'hs-henriett': { uzletag: 'headspa', nev: "Henriett Horváthné", datum: "2026.10.03.", szoveg: "Fantasztikus, csodaszép hely, szuper kedves szakemberekkel. Nagyon szeretek idejárni, szívből ajánlom őket mindenkinek. Maximális feltöltődést kap az ember.", forras: "Trustindex / Google" },
  'hs-fanni': { uzletag: 'headspa', nev: "Fanni Jáni", datum: "2026.09.19.", szoveg: "Páros headspa kezelésen voltunk, Nikinél és Vikinél. Csodálatosak a lányok, nagyon értenek a munkájukhoz, nagyon el tudtunk lazulni. Köszönjük az élményt, biztosan jövünk még.", forras: "Trustindex / Google" },
  'hs-viktoria': { uzletag: 'headspa', nev: "Viktória Fodor", datum: "2026.09.16.", szoveg: "Isteni élmény volt, egy relaxálós páros japanese head spa kezelésen vettünk részt anyukámmal. Köszönjük szépen!", forras: "foglalas/paros-headspa-budapest-uj.html" },
  'hs-reka-czako': { uzletag: 'headspa', nev: "Réka Czakó", datum: "2026.08.21.", szoveg: "Párban mentünk anyukámmal, szülinapomra kaptam ajándékba. Nagyon jól éreztük magunkat teljesen ki tudtunk kapcsolódni, mindenki nagyon kedves és segítőkész volt. A hajam szép, fényes, illatos lett. Az én kezelőm Czakó Vivien volt így a névrokonság egyből meg is hozta a jó hangulatot, biztosan jövünk máskor is. Köszönjük szépen!", forras: "Trustindex / Google" },
  'hair-eva': { uzletag: 'hair', nev: "Éva Varju", datum: "2026.08.18.", szoveg: "Nagyon kedves és segítőkész csapat, külön szeretném kiemelni Evelint, aki rendkívül hozzáértően és precízen végzi a munkáját. Nagyon elégedett vagyok, szívből ajánlom mindenkinek!", forras: "Trustindex / Google" },
  'altalanos-ildiko': { uzletag: 'altalanos', nev: "Ildikó Tóth", datum: "2026.08.24.", szoveg: "csodálatos volt a környezet, a kezelés fantasztikus, az ott dolgozók kedvesek és nagyon hozzáértők, köszönöm", forras: "Trustindex / Google" },
  'altalanos-bea': { uzletag: 'altalanos', nev: "Bea Zöld", datum: "2026.09.05.", szoveg: "Nagyon szép, igényes a hely. A személyzet figyelmes. Szuper élményben volt részünk!", forras: "Trustindex / Google" },
  'altalanos-zsofia': { uzletag: 'altalanos', nev: "Zsófia Tábor", datum: "2026.10.03.", szoveg: "Elképeztő jó kikapcsolódás. Mindenkinek ajánlom a helyet. Szuper professzionális. Csend és nyugalom van. Profi kezelők.", forras: "Trustindex / Google" },
  'altalanos-renata': { uzletag: 'altalanos', nev: "Renáta Gyarmati", datum: "2026.09.05.", szoveg: "Szuper hely, kedves személyzettel", forras: "Trustindex / Google" },
  'hair-viki': { uzletag: 'hair', nev: "Viki Zolcer", datum: "2026.08.17.", szoveg: "Evelinnél voltam, nagyon profi, ügyes és kedves! Mindenkinek csak ajánlani tudom!🥰", forras: "Trustindex / Google" },
});
